default: &default
  adapter: postgresql
  database: porksnout_<%= Rails.env %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", "5") %>
  timeout: 5000

development:
  <<: *default

production:
  <<: *default
